package com.whiterabbit.appennino.com.whiterabbit.appennino.actions;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Parcel;
import com.whiterabbit.postman.commands.RestServerRequest;
import com.whiterabbit.postman.exceptions.ResultParseException;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 2/2/13
 * Time: 12:10 PM
 */
public class WebcamDownloadAction implements RestServerRequest{
    String mUrl;
    String mFileName;

    public WebcamDownloadAction(String url, String fileName){
        mUrl = url;
        mFileName = fileName;
    }


    @Override
    public String getOAuthSigner() {
        return null;  // No signer:w
    }

    @Override
    public String getUrl() {
        return mUrl;
    }

    @Override
    public Verb getVerb() {
        return Verb.GET;
    }

    @Override
    public void processHttpResult(Response result, Context context) throws ResultParseException {
        Bitmap b = BitmapFactory.decodeStream(result.getStream());
        File path = context.getExternalFilesDir(null);
        File target = new File(path, mFileName);
        FileOutputStream out = null;
        try {
            out = new FileOutputStream(target);
            b.compress(Bitmap.CompressFormat.PNG, 90, out);
            out.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void addParamsToRequest(OAuthRequest request) {
        //TODO Autogenerated
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(mUrl);
        parcel.writeString(mFileName);
    }

    public static final Creator<WebcamDownloadAction> CREATOR
            = new Creator<WebcamDownloadAction>() {
        public WebcamDownloadAction createFromParcel(Parcel in) {
            return new WebcamDownloadAction(in);
        }

        public WebcamDownloadAction[] newArray(int size) {
            return new WebcamDownloadAction[size];
        }
    };

    public WebcamDownloadAction(Parcel in){
        mUrl = in.readString();
        mFileName = in.readString();
    }
}
