package com.whiterabbit.appennino.actions;

import android.content.Context;
import android.os.Parcel;
import com.whiterabbit.postman.commands.RestServerRequest;
import com.whiterabbit.postman.exceptions.ResultParseException;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 2/3/13
 * Time: 7:52 PM
 */
public class MeteoDownloadAction implements RestServerRequest{
    @Override
    public String getOAuthSigner() {
        return null;  //TODO Autogenerated
    }

    @Override
    public String getUrl() {
        String abetone = "http://free.worldweatheronline.com/feed/weather.ashx?q=abetone&format=json&num_of_days=2&key=18a33ad9db184852130302";
        String cimone = "http://free.worldweatheronline.com/feed/weather.ashx?q=44.19,10.70&format=json&num_of_days=2&key=18a33ad9db184852130302";
        return null;  //TODO Autogenerated
    }

    @Override
    public Verb getVerb() {
        return null;  //TODO Autogenerated
    }

    @Override
    public void processHttpResult(Response result, Context context) throws ResultParseException {
        String json = result.getBody();

       // { "data": { "current_condition": [ {"cloudcover": "3", "humidity": "73", "observation_time": "07:04 PM", "precipMM": "0.0", "pressure": "1016", "temp_C": "-1", "temp_F": "31", "visibility": "10", "weatherCode": "113",  "weatherDesc": [ {"value": "Clear" } ],  "weatherIconUrl": [ {"value": "http:\/\/www.worldweatheronline.com\/images\/wsymbols01_png_64\/wsymbol_0008_clear_sky_night.png" } ], "winddir16Point": "N", "winddirDegree": "352", "windspeedKmph": "7", "windspeedMiles": "4" } ],  "request": [ {"query": "Lat 44.19 and Lon 10.70", "type": "LatLon" } ],  "weather": [ {"date": "2013-02-03", "precipMM": "2.6", "tempMaxC": "5", "tempMaxF": "41", "tempMinC": "-1", "tempMinF": "31", "weatherCode": "113",  "weatherDesc": [ {"value": "Sunny" } ],  "weatherIconUrl": [ {"value": "http:\/\/www.worldweatheronline.com\/images\/wsymbols01_png_64\/wsymbol_0001_sunny.png" } ], "winddir16Point": "NNE", "winddirDegree": "13", "winddirection": "NNE", "windspeedKmph": "22", "windspeedMiles": "14" }, {"date": "2013-02-04", "precipMM": "0.0", "tempMaxC": "7", "tempMaxF": "45", "tempMinC": "1", "tempMinF": "34", "weatherCode": "113",  "weatherDesc": [ {"value": "Sunny" } ],  "weatherIconUrl": [ {"value": "http:\/\/www.worldweatheronline.com\/images\/wsymbols01_png_64\/wsymbol_0001_sunny.png" } ], "winddir16Point": "WSW", "winddirDegree": "237", "winddirection": "WSW", "windspeedKmph": "9", "windspeedMiles": "6" } ] }}


        //TODO Autogenerated
    }

    @Override
    public void addParamsToRequest(OAuthRequest request) {
        //TODO Autogenerated
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        //TODO Autogenerated
    }
}
