package com.whiterabbit.appennino.actions;

import android.content.Context;
import android.os.Parcel;
import com.whiterabbit.appennino.AppenninoApplication;
import com.whiterabbit.appennino.data.WebcamProviderClientExt;
import com.whiterabbit.postman.commands.RestServerRequest;
import com.whiterabbit.postman.exceptions.ResultParseException;
import org.scribe.model.OAuthRequest;
import org.scribe.model.Response;
import org.scribe.model.Verb;
import uk.co.senab.bitmapcache.BitmapLruCache;

import java.util.Date;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 2/2/13
 * Time: 12:10 PM
 */
public class WebcamDownloadAction implements RestServerRequest{
    private final long mWebcamId;
    private final String mUrl;

    public WebcamDownloadAction(String url, long webcamid){
        mUrl = url;
        mWebcamId = webcamid;
    }



    @Override
    public String getOAuthSigner() {
        return null;  // No signer
    }

    @Override
    public String getUrl() {
        return mUrl;
    }

    @Override
    public Verb getVerb() {
        return Verb.GET;
    }

    @Override
    public void processHttpResult(Response result, Context context) throws ResultParseException {
        // TODO Adjust size
        BitmapLruCache cache = AppenninoApplication.getApplication().getBitmapCache();
        cache.put(mUrl, result.getStream());
        WebcamProviderClientExt.updateWebcamLastUpdate(mWebcamId, new Date(), context);
    }

    @Override
    public void addParamsToRequest(OAuthRequest request) {
        //TODO Autogenerated
    }

    @Override
    public int describeContents() {
        return 0;  //TODO Autogenerated
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(mUrl);
        parcel.writeLong(mWebcamId);
    }

    public static final Creator<WebcamDownloadAction> CREATOR
            = new Creator<WebcamDownloadAction>() {
        public WebcamDownloadAction createFromParcel(Parcel in) {
            return new WebcamDownloadAction(in);
        }

        public WebcamDownloadAction[] newArray(int size) {
            return new WebcamDownloadAction[size];
        }
    };

    private WebcamDownloadAction(Parcel in){
        mUrl = in.readString();
        mWebcamId = in.readLong();
    }
}
