package com.whiterabbit.appennino;

import android.content.Intent;
import android.os.Bundle;
import com.actionbarsherlock.app.SherlockFragmentActivity;
import com.whiterabbit.appennino.com.whiterabbit.appennino.actions.WebcamDownloadAction;
import com.whiterabbit.postman.ServerInteractionHelper;
import com.whiterabbit.postman.ServerInteractionResponseInterface;
import com.whiterabbit.postman.exceptions.SendingCommandException;

/**
 * Created with IntelliJ IDEA.
 * User: fedepaol
 * Date: 1/31/13
 * Time: 11:59 PM
 */
public class DetailView extends SherlockFragmentActivity implements ServerInteractionResponseInterface {
    public final String URL = "com.whiterabbit.appennino.url";
    public final String TITLE = "com.whiterabbit.appennino.title";
    public final String FILENAME = "com.whiterabbit.appennino.filename";

    String mUrl;
    String mTitle;
    String mFileName;

    WebcamDetailFragment mDetailFragment;
    ServerInteractionHelper mServerHelper;

    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.webcam_detail);

        Intent i = getIntent();
        mUrl = i.getStringExtra(URL);
        mTitle = i.getStringExtra(TITLE);
        mFileName = i.getStringExtra(FILENAME);

        mServerHelper = ServerInteractionHelper.getInstance();

        mDetailFragment = (WebcamDetailFragment) getSupportFragmentManager().findFragmentById(R.id.webcam_detail_fragment);
    }

    @Override
    protected void onResume() {
        super.onResume();    // Autogenerated
        mServerHelper.registerEventListener(this, this);
        if(mServerHelper.isRequestAlreadyPending(mUrl)){
            // TODO Show pending
        }else{
            try {
                mServerHelper.sendRestAction(this, mUrl, new WebcamDownloadAction(mUrl, mFileName));
                // TODO Show pending request
            } catch (SendingCommandException e) {
                // TODO Handle failure
            }
        }
    }

    @Override
    public void onServerResult(String result, String requestId) {
        if(requestId.equals(mUrl)){
            mDetailFragment.update(mTitle, mFileName);
        }
    }

    @Override
    public void onServerError(String result, String requestId) {
        //TODO Autogenerated
    }

    @Override
    protected void onPause() {
        super.onPause();
        ServerInteractionHelper.getInstance().unregisterEventListener(this, this);
    }
}
